apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: spring-boot-app
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
      nodePort: 30090
  type: NodePort
